pipeline {
    agent any
    /* {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }*/
    stages {
        stage('Build') {
            steps {
               echo "this is build stage"
                // sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo "this is test stage "
                // sh 'mvn test'
            }
           /* post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            } */
        }
        stage('deploy') {
            steps {
               echo "this is deploy stage"
            }
        }
       /* stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }*/
    }
}
